### ISSUE TITLE
Use of "_ensureIndex"

### ISSUE THREAD

**Issue by tlianza** [meteor-typescript/meteor-typescript-libs#11]
I'm guessing this isn't present because it's an "internal" feature, but I think many people use _ensureIndex to make sure their collections are properly indexed on startup.  It would be great to get this in the typescript libs.  Especially *because* it might change in the future, having a compiler catch our use of it would be great.

https://groups.google.com/forum/#!msg/meteor-talk/8PvWXKocIGI/kjPn8vQJ6DQJ

**Comment by fullflavedave** [comment]
In general, I don't think we want to add definitions for internal methods.  The make process for this package automatically creates the definitions from the public Meteor API, so adding internal methods requires adding an exception case that has to be verified and maintained separately every time a new release comes out.

I'll suggest we make an exception in this case since:
- a Meteor core dev suggested you use this method
- it would be difficult to add this definition on your own 

This should be released later today.

**Comment by fullflavedave** [comment]
Closing since this is now fixed in version 1.0.13 on atmosphere.

**Comment by tlianza** [comment]
Wow... that's amazing. Thank you so much!
