### ISSUE TITLE
Update package.js to include all files

### ISSUE THREAD

**Issue by consideRatio** [meteor-typescript/meteor-typescript-libs#42]
I noticed flowRouter.d.ts existed in the definitions folder, but it was not built. Perhaps because an outdated package.js files listing all packages except some new ones such as flowRouter.d.ts?

**Comment by consideRatio** [comment]
I made this pull request for this issue:

https://github.com/meteor-typescript/meteor-typescript-libs/pull/43

**Comment by consideRatio** [comment]
Perhaps an enhancement can be made to package.js file, so it adds all available definition files in the folder, without having to be updated manually?

**Comment by consideRatio** [comment]
#### Background
I'm looking to contribute by systematically creating custom .d.ts files for the various meteor packages I'm using, such as SimpleSchema for example. If some changes could be made to enable me to send a pull request that only adds a .t.ds file, that would be awesome!

#### Current issues for just adding a .t.ds file
1. all-definitions.d.ts is manually updated
2. package.js is manually updated with .d.ts files

#### Suggestion
* Automize generation of all-definitions.d.ts and package.js content
* How? By automatically adding stuff based on the directories the files resides in

**Comment by fullflavedave** [comment]
That sounds like a good suggestion to me since there have been other instances of mismatches between the definition files, all-definitions.d.ts, and package.js.  I'm on vacation with the family right now and won't have a chance to work on it for the next 10 days, but I should have a chance to work on this and the other outstanding issues when I return.
